<?php
declare(strict_types=1);
/**
 * EmployeesApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  BhrSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BambooHR API
 *
 * BambooHR API documentation. https://www.bamboohr.com/api/documentation/
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BhrSdk\Test\Api;

use BhrSdk\Api\EmployeesApi;
use BhrSdk\Configuration;
use BhrSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * EmployeesApiTest Class Doc Comment
 *
 * @category Class
 * @package  BhrSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EmployeesApiTest extends TestCase {
	/**
	 * Setup before running any test cases
	 */
	public static function setUpBeforeClass(): void {
	}

	/**
	 * Setup before running each test case
	 */
	public function setUp(): void {
	}

	/**
	 * Clean up after running each test case
	 */
	public function tearDown(): void {
	}

	/**
	 * Clean up after running all test cases
	 */
	public static function tearDownAfterClass(): void {
	}

	public function testGetEmployeeDeserializesToGenericObject(): void {
		$decoded = json_decode('{"id":"123","firstName":"Jane","customField":42}');
		$result = ObjectSerializer::deserialize($decoded, 'object', []);

		self::assertIsArray($result);
		self::assertSame('123', $result['id']);
		self::assertSame('Jane', $result['firstName']);
		self::assertSame(42, $result['customField']);
	}

	public function testUpdateEmployeeRequestSerializesPayloadAsJson(): void {
		$api = new EmployeesApi(null, Configuration::getDefaultConfiguration());

		$payload = (object) [
			'firstName' => 'Jane',
			'lastName' => 'Doe',
			'customField' => 42,
		];

		$request = $api->updateEmployeeRequest('123', $payload, EmployeesApi::CONTENT_TYPES['updateEmployee'][0]);

		self::assertSame('POST', $request->getMethod());
		self::assertStringContainsString('/api/v1/employees/123', (string) $request->getUri());
		self::assertStringContainsString('application/json', $request->getHeaderLine('Content-Type'));

		$body = (string) $request->getBody();
		$decoded = json_decode($body, true);
		self::assertIsArray($decoded);
		self::assertSame('Jane', $decoded['firstName'] ?? null);
		self::assertSame('Doe', $decoded['lastName'] ?? null);
		self::assertSame(42, $decoded['customField'] ?? null);
	}

	/**
	 * Test case for addEmployee
	 *
	 * Add Employee.
	 *
	 */
	public function testAddEmployee(): void {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}

	/**
	 * Test case for getCompanyInformation
	 *
	 * Get Company Information.
	 *
	 */
	public function testGetCompanyInformation(): void {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}

	/**
	 * Test case for getEmployee
	 *
	 * Get Employee.
	 *
	 */
	public function testGetEmployee(): void {
		self::markTestSkipped('Covered by testGetEmployeeDeserializesToGenericObject');
	}

	/**
	 * Test case for getEmployeesDirectory
	 *
	 * Get Employee Directory.
	 *
	 */
	public function testGetEmployeesDirectory(): void {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}

	/**
	 * Test case for getEmployeesList
	 *
	 * Get Employees.
	 *
	 */
	public function testGetEmployeesList(): void {
		// TODO: implement
		self::markTestIncomplete('Not implemented');
	}

	/**
	 * Test case for updateEmployee
	 *
	 * Update Employee.
	 *
	 */
	public function testUpdateEmployee(): void {
		self::markTestSkipped('Covered by testUpdateEmployeeRequestSerializesPayloadAsJson');
	}
}
